// Auto-generated defensibility handbook content. Data science perspective; capabilities referenced by name. v2: praxis outline embedded.
const DS_DEFENSIBILITY = {
 "title": "Statistical Defensibility - A Data Science Perspective on PCEIF",
 "intro": "This handbook explains how every analytical capability in Lin Opus Gubernatio is designed, what uncertainty model it rests on, and how it is validated. It is organized by data science method, not by module number: readers meet the probabilistic reasoning first and the framework second. PCEIF (Probabilistic Capital-project Executive Intelligence Framework) fuses three signal types - EVM forecasting, statistical anomaly detection, and NLP document-signal extraction - into governed status verdicts through evidence fusion, with a human judgment layer recording every concurrence or override. The research artifact is evaluated under a Design Science Research methodology with qualitative validation from practicing professionals.",
 "oneSentence": "PCEIF does not dress business rules as statistics; it separates estimation, calibrated measurement, and evidence combination under epistemic uncertainty, and validates each by the standard appropriate to its tier.",
 "governanceAxis": [
  [
   "NIST AI RMF",
   "Govern: controlled module registry and human Judgment Record. Map: tier taxonomy with per-capability purpose and oversight class. Measure: band harness, calibration probes, extraction audit agreement, seeded-detection tests. Manage: escalation logic, abstention discipline, human concur or override."
  ],
  [
   "Explainable AI principles",
   "Every capability declares its explanation method: rule traces and evidence chains for deterministic logic, posterior summaries for Bayesian estimation, score decompositions for anomaly detection. Knowledge limits are implemented literally as abstention on missing inputs."
  ],
  [
   "AI management and risk standards",
   "Versioned backend releases, single-change pull requests, honest commit history, no silent failures, and single-source status derivation constitute the lifecycle management evidence."
  ],
  [
   "Model cards and datasheets",
   "Each capability entry in this handbook is its model card; the 27-document ingestion manifest with raw-facts-only authoring rules is the dataset datasheet for the synthetic corpus."
  ],
  [
   "Provenance",
   "Every extracted signal traces from field to source document to source passage; upload events are preserved across resets and audit-trail completeness is itself scored."
  ]
 ],
 "accreditation": "Accreditation is layered along two axes. Statistical axis: every method traces to a citable primary source or published practice standard; every threshold is exogenous or calibrated and proven by an automated band harness against live code; every stochastic capability carries a stated validation test; fusion behavior is verified end to end by the calibration probe protocol. Governance axis: the platform is documented as a governed system of systems with per-capability explainability methods, oversight classifications, failure-mode registers, provenance chains, and a human judgment record gating every recommendation. No capability claims a statistical property it does not have.",
 "sections": [
  {
   "tier": 1,
   "title": "Stochastic Models",
   "description": "Explicit probability models. Outputs are distributions, intervals, or detections with controlled error rates. Validated by convergence checks, seeded-detection tests, holdout error, and simulation V&V.",
   "families": [
    {
     "key": "mc",
     "label": "Stochastic Simulation (Monte Carlo)",
     "uncertainty": "Propagates input uncertainty by repeated sampling from assumed input distributions; output is an empirical distribution of the target quantity from which percentiles (P50/P80) and exceedance probabilities are read.",
     "course": "SEAS 8220 Monte Carlo unit: values for a random variable generated by sampling from a probability distribution; purpose is to generate the output distribution, not a point estimate.",
     "assumptions": "Input distributions and independence structure are assumed, not estimated from large samples; results are conditional on those assumptions. Convergence requires sufficient iterations (LLN).",
     "validation": "Traceable to standard risk-analysis practice (AACE RP 41R-08 / NASA cost-risk guidance). Validated by convergence checks (stability of percentiles across iteration counts) and sensitivity of outputs to input-distribution choices.",
     "explainability": "Convergence trace + input-distribution disclosure + tornado of input contributions; percentile outputs shown with iteration-stability bands.",
     "oversight": "Inform/estimate \u2014 forecasts inform decisions; never auto-escalates.",
     "failureModes": "Non-convergence; unrealistic input distributions; ignored correlations understating tails; seed non-reproducibility.",
     "detProb": "Deterministic: model equations, percentile extraction. Probabilistic: input sampling, output distribution.",
     "applied": [
      {
       "name": "Monte Carlo EAC Forecast",
       "note": "Samples CPI/SPI perturbations around reported values to produce an EAC distribution; the reported EAC is presented as a percentile within it, not a certainty.",
       "qa": [
        [
         "Why simulate when EAC = BAC/CPI is exact?",
         "The formula is exact given CPI, but CPI is a noisy period measurement. Simulation propagates that measurement uncertainty into a forecast interval \u2014 the same argument as reporting a CI rather than a point estimate."
        ]
       ]
      },
      {
       "name": "Schedule Risk Analysis P80",
       "note": "Monte Carlo over activity-duration distributions; reports P80 completion vs contractual date.",
       "qa": [
        [
         "Why P80 not P50?",
         "P50 is even odds; governance convention (GAO/DoD) funds to ~P70-P80 to control schedule overrun probability. The percentile choice is a risk-appetite policy, stated as such."
        ]
       ]
      },
      {
       "name": "Cost Risk Analysis P80",
       "note": "Monte Carlo over cost-element distributions; P80 cost vs budget+contingency.",
       "qa": [
        [
         "Correlation between cost elements?",
         "Applied correlation matrix (default positive pairwise correlation) because independence understates tail risk \u2014 the classic CRA critique, addressed and documented."
        ]
       ]
      }
     ]
    },
    {
     "key": "bayes",
     "label": "Bayesian Updating",
     "uncertainty": "Combines a prior belief (baseline estimate) with observed performance evidence via Bayes' theorem; the posterior narrows as evidence accumulates, giving a probability-weighted forecast rather than a point value.",
     "course": "Extends the course's conditional-probability foundation (P(A|B)) \u2014 the same law of total probability used in the probability weeks, applied sequentially.",
     "assumptions": "Prior choice matters when data are sparse (early project periods); likelihood model assumes reported CPI/SPI are unbiased measurements of true performance.",
     "validation": "Bayesian EAC methods are established in EVM literature (e.g., Kim & Reinschmidt). Validated by comparing posterior forecasts against realized finals on seeded multi-period histories.",
     "explainability": "Posterior summaries (mean, credible interval), prior-vs-posterior overlay, posterior predictive checks.",
     "oversight": "Inform/forecast \u2014 advisory forecast alongside deterministic EAC.",
     "failureModes": "Prior dominance with sparse data; miscalibrated likelihood; convergence issues if sampled.",
     "detProb": "Deterministic: model structure, update rule. Probabilistic: prior, likelihood, posterior.",
     "applied": [
      {
       "name": "Bayesian EAC",
       "note": "Prior = baseline BAC-implied performance; likelihood = observed period CPIs; posterior EAC tightens as periods accrue.",
       "qa": [
        [
         "How sensitive is it to the prior?",
         "Deliberately reported: early-period forecasts show prior dominance and wide intervals; by period 4-5 the likelihood dominates. That sensitivity is displayed, not hidden \u2014 the honest Bayesian answer."
        ]
       ]
      }
     ]
    },
    {
     "key": "spc",
     "label": "Statistical Process Control / Sequential Detection",
     "uncertainty": "Treats the periodic performance index as a monitored process; cumulative deviations from a target are accumulated (CUSUM) so small persistent shifts trigger before any single period looks alarming. Detection threshold trades Type I error (false alarm) against Type II error (missed shift) \u2014 the course's error framework applied sequentially.",
     "course": "Directly maps to W5 (Type I/II errors, significance) \u2014 a CUSUM breach is a rejection of the 'process on target' null with a controlled false-alarm rate.",
     "assumptions": "Requires a multi-period history; assumes period observations are comparable and approximately independent after detrending; reference value k and decision interval h are design choices.",
     "validation": "CUSUM (Page 1954) is a canonical sequential test; parameters justified by Average Run Length reasoning. Validated on seeded histories with known injected shifts.",
     "explainability": "Rule trace: cumulative-sum path plotted against decision interval h; breach point identified on the period axis.",
     "oversight": "Flag \u2014 a breach flags Red for the module; escalation remains human-decided.",
     "failureModes": "Autocorrelated periods inflating false alarms; restart/reset errors (the v10.24 phantom-breach bug is the documented case study); parameter drift.",
     "detProb": "Deterministic: CUSUM recursion, threshold compare. Probabilistic: ARL design of k and h.",
     "applied": [
      {
       "name": "CUSUM Anomaly Monitor",
       "note": "Accumulates SPI deviations from target across project.history; breach = Red. Reads multi-period series, so it abstains on single-period projects.",
       "qa": [
        [
         "What is your false-alarm rate?",
         "Set by the decision interval h via Average Run Length design: h chosen so in-control ARL is long relative to reporting cadence. The seeded-history tests demonstrate detection of injected 0.03\u20130.05 SPI shifts without alarming on stable series."
        ]
       ]
      }
     ]
    },
    {
     "key": "ts",
     "label": "Time-Series Estimation / Forecasting",
     "uncertainty": "Models the observed index series as signal plus noise; the filter/model separates persistent trend from period noise and yields a forecast with quantified uncertainty (state variance / prediction interval).",
     "course": "Builds on the course's sampling-variability idea: any single period's SPI is one noisy draw; the estimator pools information across periods exactly as a sample mean pools draws, but with recency weighting.",
     "assumptions": "Kalman assumes linear-Gaussian state evolution; ARIMA assumes (weak) stationarity after differencing. Short series (<6 periods) yield wide, honest uncertainty \u2014 the module abstains rather than overstate confidence.",
     "validation": "Standard estimation theory (Kalman 1960; Box-Jenkins). Validated by one-step-ahead holdout error on seeded histories.",
     "explainability": "Fitted-vs-observed series plot, one-step-ahead residuals, state variance / prediction interval disclosure.",
     "oversight": "Inform \u2014 smoothed/forecast series inform trend judgment.",
     "failureModes": "Short-series overfit (mitigated by abstention floor); nonstationarity; structural breaks (scope change) violating model.",
     "detProb": "Deterministic: filter/model equations. Probabilistic: noise variances, prediction intervals.",
     "applied": [
      {
       "name": "Kalman Filter SPI Smoother",
       "note": "State = latent true SPI; observation = reported period SPI with noise variance R; filter output is smoothed SPI with variance.",
       "qa": [
        [
         "Why Kalman over a moving average?",
         "A moving average has fixed lag and no uncertainty output. The Kalman gain adapts weighting to signal/noise ratio and yields a variance \u2014 needed downstream so fusion can weight this evidence by confidence."
        ]
       ]
      },
      {
       "name": "ARIMA CPI Forecast",
       "note": "Low-order ARIMA on cpiHistory; abstains below minimum series length rather than fitting to 3 points.",
       "qa": [
        [
         "Is stationarity plausible for CPI?",
         "CPI is bounded and mean-reverting in stable execution, so differencing-to-stationarity is defensible; the module's abstention rule prevents fitting where the assumption can't be checked."
        ]
       ]
      },
      {
       "name": "Earned Schedule",
       "note": "Converts SV from dollars to time (ES = time at which PV equaled current EV); Green at >=0.95. Corrects the known end-of-project SPI($) distortion.",
       "qa": [
        [
         "Why add ES if you have SPI?",
         "SPI($) converges to 1.0 at completion regardless of lateness \u2014 a documented bias. ES(t) is the literature's correction (Lipke 2003); including both shows awareness of estimator bias, a course-central concept."
        ]
       ]
      },
      {
       "name": "Regression to Mean CPI",
       "note": "Projects future CPI as weighted pull toward portfolio/historical mean; needs cpiHistory.",
       "qa": [
        [
         "Isn't this just shrinkage?",
         "Yes \u2014 deliberately. Early extreme CPIs are partly noise; shrinkage estimators reduce MSE (Stein-type argument). The module names the phenomenon professors already teach: extreme observations regress."
        ]
       ]
      }
     ]
    },
    {
     "key": "ml",
     "label": "Machine-Learning Anomaly Detection (Portfolio Level)",
     "uncertainty": "Unsupervised: learns the portfolio's joint feature distribution and scores projects by atypicality (Isolation Forest path length; distance-based outlier scores). Output is a relative anomaly score, not a classification with claimed error rates.",
     "course": "Maps to the course's EDA and distribution weeks: an outlier is an observation improbable under the empirical portfolio distribution; the isolation-forest score is a computational proxy for that tail probability.",
     "assumptions": "Requires 3+ projects (stated explicitly; modules abstain below that). Small-n portfolios give unstable scores \u2014 reported as exploratory signals, never as sole escalation triggers.",
     "validation": "Isolation Forest (Liu et al. 2008) peer-reviewed. Validated by seeding a known-deviant synthetic project and confirming it ranks top of the anomaly ordering.",
     "explainability": "Anomaly-score ranking with per-feature contribution (path-length or distance decomposition); flagged project click-through to contributing signals.",
     "oversight": "Inform/exploratory \u2014 never a sole escalation trigger; explicitly ranked-evidence only at portfolio n.",
     "failureModes": "Small-n instability; feature-scaling sensitivity; masking/swamping among outliers; concept drift as portfolio composition changes.",
     "detProb": "Deterministic: scoring given fitted model. Probabilistic: model fitting on the empirical portfolio distribution.",
     "applied": [
      {
       "name": "Isolation Forest",
       "note": "Portfolio-level multivariate anomaly detection over project feature vectors.",
       "qa": [
        [
         "n=12 projects \u2014 is ML defensible?",
         "Framed honestly: with small n these are exploratory ranking tools, never sole escalation triggers; the 3+-project abstention floor is coded, and the praxis states the small-n limitation explicitly. The defense is scope discipline, not sample size."
        ]
       ]
      },
      {
       "name": "Portfolio Outlier Detection",
       "note": "Distance/density outlier scoring (complementary to PH.1's tree-based isolation).",
       "qa": []
      },
      {
       "name": "Signal Trajectory Classifier",
       "note": "Classifies multi-period signal trajectories (improving/stable/deteriorating) across the portfolio.",
       "qa": []
      },
      {
       "name": "Cross-project Pattern Detector",
       "note": "Detects shared deterioration patterns across projects (common-cause vs project-specific).",
       "qa": []
      },
      {
       "name": "Anomaly Score",
       "note": "Composite portfolio anomaly index rolled into Portfolio Health.",
       "qa": []
      }
     ]
    },
    {
     "key": "sim",
     "label": "Systems Simulation (DES / ABM / Queueing / SD)",
     "uncertainty": "Mechanistic stochastic models of project workflows: arrival/service processes (queueing), entity flows (DES), interacting agents (ABM), feedback loops (rework). Outputs are distributions of throughput/delay under sampled randomness.",
     "course": "Queueing sits directly on the course's Poisson-process unit (arrivals at rate lambda; exponential interarrivals). DES/ABM are Monte Carlo over structured models.",
     "assumptions": "Arrival/service distributions parameterized from document-extracted rates; structural validity (does the model topology match the real workflow) argued via practitioner interviews, not statistics.",
     "validation": "Poisson/queueing theory is canonical (M/M/1 assumptions stated); ABM/DES validated by face validation + extreme-condition tests (Sargent's simulation V&V framework \u2014 the citable accreditation standard for simulation models).",
     "explainability": "Model-structure diagram + parameter provenance table + Sargent V&V record (face validation, extreme-condition, cross-model checks); output distributions with convergence diagnostics.",
     "oversight": "Simulate \u2014 exploratory what-if engines; outputs inform, never flag directly.",
     "failureModes": "Structural invalidity (topology does not match real workflow); distributional assumption violations (non-Poisson arrivals); insufficient replications; parameter provenance gaps.",
     "detProb": "Deterministic: model structure, event logic. Probabilistic: arrival/service/duration sampling.",
     "applied": [
      {
       "name": "DSM Rework Propagation",
       "note": "Design Structure Matrix rework loops; propagates rework probability through dependency cycles. (Note: verify distinct computation vs 5.1 or dedupe \u2014 open praxis punch-list item.)",
       "qa": [
        [
         "Duplicate of 5.1?",
         "Flagged: the draft lists it at 3.2 and 5.1. Either the computations differ (cost-weighted vs flow-weighted propagation) and that must be documented, or one is removed. This is on the discrepancy punch-list \u2014 do not defend it as-is."
        ]
       ]
      },
      {
       "name": "DSM Rework Propagation",
       "note": "Flow-weighted rework propagation through the dependency matrix (see 3.2 dedupe flag).",
       "qa": [
        [
         "Same as 3.2?",
         "On the punch-list \u2014 see 3.2. Defense posture: acknowledge and resolve before the review, do not improvise a distinction live."
        ]
       ]
      },
      {
       "name": "Rework Feedback Loop",
       "note": "System-dynamics loop: undiscovered rework stock degrading productivity.",
       "qa": [
        [
         "Validation?",
         "Sargent V&V: extreme-condition tests (zero rework -> plan trajectory; high rework -> known death-spiral shape from SD literature, Cooper's rework cycle)."
        ]
       ]
      },
      {
       "name": "Queueing Theory Bottleneck",
       "note": "M/M/c approximation of approval/inspection queues from extracted arrival and service rates.",
       "qa": [
        [
         "M/M/c assumptions?",
         "Poisson arrivals and exponential service \u2014 course-taught conditions; stated as approximations with utilization-based results robust to moderate violations."
        ]
       ]
      },
      {
       "name": "Agent-Based Supply Chain",
       "note": "Agents = suppliers/subs with stochastic lead times; emergent delay distributions.",
       "qa": [
        [
         "ABM accreditation?",
         "Face validation with practitioners plus parameter provenance from documents; positioned as exploratory (tier-1 stochastic but structural-validity-limited), per Sargent."
        ]
       ]
      },
      {
       "name": "Discrete Event Simulation",
       "note": "Workflow DES of the document-approval pipeline; outputs cycle-time distribution.",
       "qa": [
        [
         "Why DES and queueing both?",
         "Queueing gives closed-form steady-state checks; DES relaxes assumptions. Agreement between them is a verification argument (model cross-validation)."
        ]
       ]
      },
      {
       "name": "ABM Governance Layer",
       "note": "Agent-based model of governance actors (owner/CM/contractor) response latencies to signals.",
       "qa": []
      }
     ]
    }
   ]
  },
  {
   "tier": 2,
   "title": "Calibrated Indicators",
   "description": "Exact arithmetic on reported figures. Uncertainty lives in the inputs and is governed by four-tier bands acting as control limits in the statistical process control tradition, with cited practice provenance. Validated by the automated band harness and calibrated synthetic document sets.",
   "families": [
    {
     "key": "evm",
     "label": "Deterministic EVM Indicator with SPC-Calibrated Bands",
     "uncertainty": "A ratio computed exactly from reported figures (no sampling error in the arithmetic). Uncertainty enters through the inputs (measurement/reporting error in EV, AC, PV) and is handled at the governance layer: 4-tier bands act as control limits \u2014 decision thresholds calibrated to industry evidence, not p-values.",
     "course": "The honest course mapping is measurement + decision theory: the band edges are the acceptance/rejection regions of a decision rule, with band width absorbing input measurement uncertainty (analogous to a CI's margin of error around the reported index).",
     "assumptions": "Assumes the underlying document figures are accurate; PCEIF explicitly compensates via Data Integrity (Cat 9) modules that score input quality, and via DST fusion that lets weak evidence abstain.",
     "validation": "Ratios and thresholds trace to DoD EVMIG / PMI Practice Standard for EVM; the 0.95/0.92/0.88 bands align with published EVM variance-tolerance conventions. Validated by the tests.html band harness (~30 edge cases from code constants) and calibrated synthetic document sets that hit each target band.",
     "explainability": "Rule trace and evidence chain: exact formula, input values with document provenance, band edge comparison \u2014 fully auditable arithmetic.",
     "oversight": "Flag \u2014 banded status vote into fusion; no autonomous action.",
     "failureModes": "Input reporting error (garbage-in); threshold brittleness at band edges; correlated-input double counting in fusion; stale-period data.",
     "detProb": "Deterministic: entire computation. Probabilistic: none claimed \u2014 input uncertainty handled by Cat 9 weighting and band width.",
     "applied": [
      {
       "name": "TCPI",
       "note": "TCPI = (BAC-EV)/(BAC-AC); bands 1.05/1.10/1.20. Measures required future efficiency.",
       "qa": [
        [
         "Is a TCPI of 1.074 'statistically' Yellow?",
         "No test is claimed. 1.05/1.10/1.20 are decision thresholds from EVM practice (DoD guidance treats TCPI>1.10 as rarely recoverable). The band is a calibrated control limit, and the harness proves the code honors it."
        ]
       ]
      },
      {
       "name": "Variance at Completion",
       "note": "VAC = BAC - EAC, banded relative to BAC.",
       "qa": [
        [
         "Where does uncertainty appear?",
         "Through EAC: when the Monte Carlo EAC distribution is used, VAC inherits an interval; the deterministic VAC is its central value."
        ]
       ]
      },
      {
       "name": "Budget Execution Rate",
       "note": "AC burn vs time elapsed; flags under/over-execution against plan corridor 0.90-1.10.",
       "qa": [
        [
         "Why is under-spend flagged?",
         "Under-execution predicts back-loaded risk; the symmetric corridor encodes that both tails are anomalous \u2014 same logic as a two-sided test region in W4-W5."
        ]
       ]
      },
      {
       "name": "ICE Ratio",
       "note": "Independent Cost Estimate ratio vs current EAC; divergence banded.",
       "qa": [
        [
         "What makes the ICE independent?",
         "Sourced from a different document (independent estimate doc) than the EAC chain; the module is a cross-validation check between two estimators \u2014 disagreement is evidence, agreement is corroboration in the DST sense."
        ]
       ]
      },
      {
       "name": "Critical Path Index",
       "note": "CPLI-style ratio of critical-path performance; Green >=0.95 with EVM bands.",
       "qa": [
        [
         "Shares inputs with SPI \u2014 double counting?",
         "Acknowledged correlation; fusion's design (abstention, Red-weighting, dominance at project level) limits the effect, and the limitation is stated in the praxis Limitations topic."
        ]
       ]
      },
      {
       "name": "Contingency Burn Rate",
       "note": "Contingency drawdown vs risk-retirement schedule.",
       "qa": [
        [
         "Null model?",
         "Linear or risk-register-phased drawdown; faster burn than retired risk is the flag condition."
        ]
       ]
      },
      {
       "name": "Labor Productivity Index",
       "note": "Earned hours / actual hours, EVM-style bands.",
       "qa": [
        [
         "Measurement error?",
         "Timesheet-derived; Cat 9 timeliness/consistency scores down-weight stale inputs in fusion."
        ]
       ]
      },
      {
       "name": "Material Cost Variance",
       "note": "Committed+actual material vs budget line, banded.",
       "qa": [
        [
         "Inflation confound?",
         "Separated: 3.10 normalizes for index inflation so 3.5 isolates execution variance \u2014 a deliberate decomposition of variance sources."
        ]
       ]
      },
      {
       "name": "Overhead Absorption Rate",
       "note": "Indirects absorbed vs plan corridor.",
       "qa": [
        [
         "Why include indirects?",
         "Overhead under-absorption is a leading insolvency indicator in contracting; corridor sourced from surety-industry practice."
        ]
       ]
      },
      {
       "name": "Analogous Estimating Ratio",
       "note": "Current unit cost vs analog project benchmark.",
       "qa": [
        [
         "Just one analog?",
         "Benchmark band widened to reflect analog uncertainty; presented as corroborative evidence, low fusion mass."
        ]
       ]
      },
      {
       "name": "Parametric Cost Index",
       "note": "Cost vs parametric model (e.g., $/sf regression) residual banded.",
       "qa": [
        [
         "Where's the regression?",
         "The parametric baseline is a fitted relationship from sector data; the module scores the residual \u2014 a standardized-residual outlier check, W2/EDA logic."
        ]
       ]
      },
      {
       "name": "Inflation Adjustment Index",
       "note": "Escalation-normalized cost ratio using published indices.",
       "qa": [
        [
         "Source?",
         "Published construction cost indices (ENR/BLS); exogenous, citable, no estimation performed in-module."
        ]
       ]
      }
     ]
    },
    {
     "key": "sched",
     "label": "Deterministic Schedule Analytic with Calibrated Bands",
     "uncertainty": "Computed from schedule data (network, float, milestones); stochastic where noted (SRA P80 is Monte Carlo over activity durations). Bands encode planning-tolerance conventions as control limits.",
     "course": "SRA P80 maps directly to the Monte Carlo unit (percentile of a simulated distribution); PERT criticality uses the Beta/PERT three-point estimate \u2014 an explicit probability model of activity duration taught in the distributions weeks.",
     "assumptions": "Network logic and reported percent-complete are taken as ground truth; MTA slip bands (0/7/14 days, worst>21 override) are governance conventions, not estimated quantities.",
     "validation": "PERT/CPM and SRA are standard (PMI SP for Scheduling; GAO Schedule Assessment Guide). Band edges validated in the band harness; SRA validated by convergence checks.",
     "explainability": "Rule trace with schedule-data provenance; for SRA/PERT, distribution disclosure and percentile trace as per Monte Carlo class.",
     "oversight": "Flag \u2014 status vote into fusion.",
     "failureModes": "Bad network logic in source schedule; percent-complete gaming; the planned%>actual% authoring trap (documented SPI cascade); band brittleness.",
     "detProb": "Deterministic: network arithmetic, bands. Probabilistic: only PERT variance and SRA sampling where applicable.",
     "applied": [
      {
       "name": "PERT Network Criticality",
       "note": "Beta/PERT three-point durations ((O+4M+P)/6, variance ((P-O)/6)^2); path criticality from mean/variance of path sums.",
       "qa": [
        [
         "Why Beta-PERT?",
         "It is the canonical elicitation distribution for expert three-point estimates; the course's expectation/variance machinery applies directly, and the CLT justifies treating path sums as approximately normal."
        ]
       ]
      },
      {
       "name": "Line of Balance",
       "note": "Production-rate consistency across repetitive units; slope deviation banded.",
       "qa": [
        [
         "Statistical content?",
         "None claimed \u2014 it is a deterministic production analytic; its band is a planning tolerance. Tier-2 honesty: not every governance signal is an estimator."
        ]
       ]
      },
      {
       "name": "CCPM Buffer Health",
       "note": "Buffer consumption vs chain completion; fever-chart zones are the bands.",
       "qa": [
        [
         "Aren't fever zones arbitrary?",
         "They are published CCPM conventions (Goldratt); PCEIF cites them as adopted practice standards, and the zone edges are covered by the band harness."
        ]
       ]
      },
      {
       "name": "Schedule Compression Index",
       "note": "Remaining work vs remaining duration relative to plan.",
       "qa": [
        [
         "Uncertainty handling?",
         "Input uncertainty only; feeds fusion as one bounded vote, never a standalone verdict."
        ]
       ]
      },
      {
       "name": "Float Consumption Rate",
       "note": "Total float burn per period vs linear allowance.",
       "qa": [
        [
         "Why linear allowance?",
         "A neutral null model: consuming float faster than uniformly is early warning. Analogous to testing observed slope against a null slope."
        ]
       ]
      },
      {
       "name": "S-Curve Deviation",
       "note": "Actual vs planned cumulative progress; requires planned% <= actual% authoring discipline (the known SPI trap).",
       "qa": [
        [
         "Known failure mode?",
         "Yes \u2014 if synthetic docs state planned%>actual%, SPI recomputes below 1 and cascades. Documented as an input-integrity constraint, itself an example of why Cat 9 exists."
        ]
       ]
      },
      {
       "name": "Milestone Trend Analysis",
       "note": "Slip in days per milestone across periods; bands 0/7/14, worst-slip>21 override.",
       "qa": [
        [
         "Why an override?",
         "A single catastrophic milestone should not be averaged away \u2014 a max-statistic guard against masking, the same reason worst-status-wins governs categories."
        ]
       ]
      },
      {
       "name": "Look-Ahead Schedule Health",
       "note": "Near-horizon activity readiness ratio.",
       "qa": [
        [
         "Evidence value?",
         "Leading indicator with short horizon; weighted accordingly in fusion \u2014 low mass, early signal."
        ]
       ]
      },
      {
       "name": "Resource Loading Index",
       "note": "Planned vs available resource profile ratio, corridor 0.90-1.10.",
       "qa": [
        [
         "Two-sided again?",
         "Yes \u2014 overload predicts burnout/quality loss, underload predicts drift; symmetric corridor mirrors a two-sided rejection region."
        ]
       ]
      }
     ]
    },
    {
     "key": "gov",
     "label": "Compliance / Governance Threshold",
     "uncertainty": "Binary or banded checks against externally defined regulatory thresholds. No estimation involved; the uncertainty question is data completeness, delegated to Cat 9 scores.",
     "course": "Decision-rule framing only; the statistics live upstream in the indices being checked.",
     "assumptions": "Thresholds are exogenous (FAR, OMB A-11, EVM reporting mandates) \u2014 the module's validity is fidelity to the cited source, which is the cleanest possible accreditation.",
     "validation": "Direct citation to FAR clauses / OMB Circular A-11 / agency EVM reporting thresholds. Validated by test cases at threshold boundaries.",
     "explainability": "Rule trace to cited regulatory text: threshold source clause, input value, pass/fail \u2014 the cleanest audit chain in the system.",
     "oversight": "Flag \u2014 compliance breaches flag; remediation is human.",
     "failureModes": "Regulatory-threshold updates not propagated (stale citations); misclassification of contract type; incomplete source documents.",
     "detProb": "Deterministic: entire check. Probabilistic: none.",
     "applied": [
      {
       "name": "FAR Threshold Monitor",
       "note": "Checks contract actions against FAR dollar/approval thresholds.",
       "qa": []
      },
      {
       "name": "OMB A-11 Check",
       "note": "Capital programming exhibit completeness per OMB Circular A-11.",
       "qa": []
      },
      {
       "name": "EVM Reporting Threshold",
       "note": "Flags when contract size/type mandates formal EVMS reporting.",
       "qa": []
      },
      {
       "name": "Contract Modification Frequency",
       "note": "Mod rate vs sector norms; banded.",
       "qa": []
      },
      {
       "name": "Quality Compliance Index",
       "note": "Quality pass rate vs contractual quality plan.",
       "qa": []
      },
      {
       "name": "Safety Performance Index",
       "note": "Recordable-incident rate vs sector baseline (exposure-normalized).",
       "qa": [
        [
         "Incident rates are count data \u2014 model?",
         "Exposure-normalized rate with Poisson variance for the comparison band; small-count instability handled by banding on cumulative exposure."
        ]
       ]
      },
      {
       "name": "Environmental Compliance Rate",
       "note": "Environmental findings per inspection; banded.",
       "qa": []
      },
      {
       "name": "Contractor Performance Score",
       "note": "CPARS-style composite of ratings; ordinal thresholds 4/3.5/3.",
       "qa": []
      }
     ]
    },
    {
     "key": "dq",
     "label": "Data-Quality / Meta-Uncertainty Score",
     "uncertainty": "Scores the trustworthiness of the evidence base itself (missingness, timeliness, consistency). This is PCEIF's explicit handling of the course's caveat that inference is only as good as the data: these scores feed source-reliability weights into fusion.",
     "course": "W1 data-preparation unit is the direct anchor: missingness mechanisms, cleaning, and integration quality made first-class quantities.",
     "assumptions": "Completeness ratios assume the 27-document manifest defines 'complete'; consistency checks assume cross-document fields should reconcile exactly.",
     "validation": "Grounded in data-quality dimensions literature (accuracy/completeness/timeliness/consistency \u2014 Wang & Strong 1996). Validated by injecting known gaps/contradictions into synthetic sets.",
     "explainability": "Completeness/consistency scorecards with per-document and per-field drill-down; reconciliation deltas shown explicitly.",
     "oversight": "Inform + weight \u2014 scores down-weight unreliable evidence in fusion automatically; the weighting rule itself is disclosed.",
     "failureModes": "Manifest definition drift (27-doc set changes); tolerance bands too loose/tight for reconciliation; treating MNAR missingness as benign.",
     "detProb": "Deterministic: scoring rules. Epistemic: reliability weights fed to fusion.",
     "applied": [
      {
       "name": "Missing Data Index",
       "note": "Fraction of the 27-doc manifest present, weighted by module-feeding importance.",
       "qa": [
        [
         "Missingness mechanism?",
         "PCEIF treats missingness as informative (MNAR-leaning): absent risk documents on a distressed project are themselves a signal, which is why completeness feeds fusion rather than being silently imputed."
        ]
       ]
      },
      {
       "name": "Data Timeliness Score",
       "note": "Age of latest period data vs reporting cadence.",
       "qa": []
      },
      {
       "name": "Source Reliability Weighting",
       "note": "Per-source reliability weights feeding fusion mass (the Z-number reliability component operationalized).",
       "qa": []
      },
      {
       "name": "Audit Trail Completeness",
       "note": "Upload/extraction event coverage vs expected pipeline events.",
       "qa": []
      },
      {
       "name": "Information Completeness Ratio",
       "note": "Field-level extraction completeness across required inputs.",
       "qa": []
      },
      {
       "name": "Cross-document Consistency Score",
       "note": "Reconciliation checks (e.g., pay-app EV vs monthly-report EV) with tolerance bands.",
       "qa": []
      },
      {
       "name": "Reporting Frequency Index",
       "note": "Observed vs contractual reporting frequency.",
       "qa": []
      }
     ]
    },
    {
     "key": "doc",
     "label": "NLP Document-Signal Extraction with Risk Scoring",
     "uncertainty": "LLM extraction converts unstructured documents into structured fields; docRiskScore aggregates raw fact signals (dispute language, unresolved RFIs, NCR counts) into [0,1]. Extraction uncertainty is acknowledged: documents carry raw facts only (no pre-judged verdicts), and the Opus audit pass is an independent second-reader check.",
     "course": "Framed as measurement with error: extraction is the instrument; the audit pass estimates its error rate, analogous to the course's measurement-reliability discussion.",
     "assumptions": "LLM extraction can err; mitigations are the raw-facts-only authoring rule, dual-model audit, and Cat 9 consistency checks. Bands (0.30/0.70) are calibrated decision thresholds.",
     "validation": "Accredited procedurally: documented extraction prompts, audit protocol, and inter-model agreement rates on the synthetic corpus (a measurable reliability statistic professors can interrogate).",
     "explainability": "Evidence chain: extracted field \u2192 source document \u2192 source passage; audit-pass agreement rate published; docRiskScore decomposition by signal.",
     "oversight": "Flag \u2014 doc-risk bands vote into fusion; extraction disagreements surfaced for human review.",
     "failureModes": "Extraction miss/hallucination (bounded by dual-model audit); raw-facts authoring rule violations re-introducing verdict leakage; band brittleness at 0.30/0.70; per-call API cost of re-ingestion (operational constraint).",
     "detProb": "Deterministic: scoring aggregation, bands. Probabilistic/epistemic: extraction reliability, audited.",
     "applied": [
      {
       "name": "Document Risk Extraction",
       "note": "The project-level ingestion of NLP-extracted raw signals feeding docRiskScore; the EVM-category instance of the Cat 4 pipeline.",
       "qa": [
        [
         "How do you know the LLM extracted correctly?",
         "Dual-model protocol: Sonnet extracts, Opus audits independently; disagreement rate on the synthetic corpus is the measured reliability statistic. Documents carry raw facts only, so the model cannot parrot a pre-judged verdict."
        ]
       ]
      },
      {
       "name": "Document Risk Score",
       "note": "Aggregate docRiskScore in [0,1] from raw extracted facts across RFI/OAC/correspondence/risk-register/NCR docs; bands 0.30/0.70.",
       "qa": [
        [
         "How were 0.30/0.70 chosen?",
         "Calibrated on the synthetic corpus so that fact-density profiles authored to represent healthy/strained/distressed projects land in the intended bands, then face-validated with practitioners. It is a calibrated instrument, and the calibration procedure is the accreditation."
        ]
       ]
      },
      {
       "name": "RFI Velocity",
       "note": "Open-RFI aging and arrival rate; Poisson-arrival framing for rate comparison.",
       "qa": [
        [
         "Poisson justified?",
         "RFI arrivals are rare, independent-ish events in time \u2014 the course's Poisson-process conditions approximately hold; rate comparison uses the Poisson mean-variance relationship."
        ]
       ]
      },
      {
       "name": "Submittal Rejection Rate",
       "note": "Rejected/total submittals as a proportion; banded.",
       "qa": [
        [
         "Why not a proportion test?",
         "With small n per period a z-test is fragile; the band acts as a practical-significance threshold. With larger samples the same statistic supports a formal one-proportion test \u2014 stated as an extension."
        ]
       ]
      },
      {
       "name": "NCR Rate",
       "note": "Nonconformance reports per work volume; bands .15/.30/.50.",
       "qa": [
        [
         "Rate denominators?",
         "Normalized per inspection volume so projects of different sizes are comparable \u2014 the exposure adjustment any rate statistic requires."
        ]
       ]
      },
      {
       "name": "Weather Day Impact",
       "note": "Weather delay days vs contractual allowance.",
       "qa": [
        [
         "Exogenous risk?",
         "Yes \u2014 separated so weather variance is not misattributed to performance; a variance-decomposition argument."
        ]
       ]
      },
      {
       "name": "Change Order Frequency",
       "note": "CO count and value rate vs baseline expectations.",
       "qa": [
        [
         "Expectation source?",
         "Sector norms for CO value as % of contract; deviation is the signal."
        ]
       ]
      },
      {
       "name": "Dispute Escalation Index",
       "note": "Extracted dispute-language intensity trend across correspondence.",
       "qa": [
        [
         "Subjective?",
         "The extraction targets enumerable facts (claim notices, reserved rights, cure letters), not sentiment; the audit pass measures extraction agreement."
        ]
       ]
      },
      {
       "name": "Subcontractor Performance",
       "note": "Rating aggregation from reports; bands 4/3.5/3.",
       "qa": [
        [
         "Ordinal data treated how?",
         "As ordinal \u2014 banded on thresholds, never averaged as if interval-scaled without noting the assumption."
        ]
       ]
      },
      {
       "name": "Procurement Lead Time Monitor",
       "note": "Actual vs quoted lead times; late fraction banded.",
       "qa": [
        [
         "Distributional view?",
         "Lead-time overrun fraction is a censored observation problem; the module reports the empirical late fraction, honest about right-censored open orders."
        ]
       ]
      },
      {
       "name": "Specification Conflict Density",
       "note": "Extracted spec conflicts per division; density banded.",
       "qa": [
        [
         "Detection reliability?",
         "Bounded by extraction recall; reported jointly with Cat 9 completeness so a low score with poor document coverage is discounted in fusion."
        ]
       ]
      }
     ]
    },
    {
     "key": "opt",
     "label": "Decision Optimization / Scenario Analytics",
     "uncertainty": "Prescriptive layer: given fused statuses, explores trade-offs (LP, Pareto, regret). Uncertainty is carried in via scenario ranges and sensitivity matrices rather than re-estimated.",
     "course": "Sensitivity and what-if analysis extend the course's Monte Carlo logic to decision variables: vary inputs over ranges, observe decision stability.",
     "assumptions": "Objective weights and constraint sets are stakeholder inputs; results presented as decision support, never as unique optima.",
     "validation": "Standard OR methods (LP: Dantzig; Pareto/regret: Savage) with textbook provenance. Validated by hand-checkable small instances in the test harness.",
     "explainability": "Full input disclosure (objectives, weights, constraints, ranges) + solution trace; decision-stability regions shown for sensitivity outputs.",
     "oversight": "Simulate/inform \u2014 prescriptive outputs are decision support; no optimum presented as unique or binding.",
     "failureModes": "Weight-elicitation bias; infeasible constraint sets silently relaxed; OAT sensitivity missing interactions; scenario incompleteness.",
     "detProb": "Deterministic: solvers, sweeps. Probabilistic: only via scenario ranges carried in.",
     "applied": [
      {
       "name": "Sensitivity Analysis",
       "note": "One-at-a-time and range-based sensitivity of project status to input perturbations.",
       "qa": [
        [
         "OAT limitations?",
         "Acknowledged \u2014 OAT misses interactions; the tornado (5.3) and scenario matrix (10.4) partially compensate, and the limitation is documented."
        ]
       ]
      },
      {
       "name": "Tornado Risk Ranking",
       "note": "Ranks inputs by output swing across plausible ranges.",
       "qa": [
        [
         "Range provenance?",
         "Ranges from band edges and historical variation \u2014 each bar's endpoints are traceable to a documented source."
        ]
       ]
      },
      {
       "name": "Scenario Modeling",
       "note": "Named coherent scenarios (baseline/stress/recovery) recomputed end-to-end.",
       "qa": [
        [
         "Scenario probability?",
         "None assigned \u2014 scenarios are conditional analyses; assigning probabilities would overstate knowledge (a deliberate epistemic-humility choice)."
        ]
       ]
      },
      {
       "name": "Multi-Objective Optimization",
       "note": "Cost/schedule/risk trade surface over candidate interventions.",
       "qa": []
      },
      {
       "name": "Linear Programming",
       "note": "Resource reallocation LP under budget/capacity constraints.",
       "qa": []
      },
      {
       "name": "Constraint Satisfaction Analysis",
       "note": "Feasibility check of recovery plans against hard constraints.",
       "qa": []
      },
      {
       "name": "What-If Scenario Matrix",
       "note": "Grid of input perturbations x decisions with recomputed statuses.",
       "qa": []
      },
      {
       "name": "Decision Sensitivity Matrix",
       "note": "Which decisions flip under which input changes \u2014 decision-stability regions.",
       "qa": []
      },
      {
       "name": "Pareto Frontier Analysis",
       "note": "Non-dominated intervention set.",
       "qa": []
      },
      {
       "name": "Regret Minimization Index",
       "note": "Minimax-regret ranking under scenario uncertainty (Savage).",
       "qa": []
      }
     ]
    }
   ]
  },
  {
   "tier": 3,
   "title": "Uncertainty Representation and Evidence Fusion",
   "description": "Epistemic uncertainty: belief masses, membership degrees, and abstention for missing evidence. Validated by primary-source axioms, documented parameterization, stability analysis, and practitioner face validation.",
   "families": [
    {
     "key": "fuzzy",
     "label": "Non-Probabilistic Uncertainty Representation",
     "uncertainty": "Represents epistemic uncertainty (vague, conflicting, or partially trusted evidence) that classical probability handles poorly: membership degrees, belief/plausibility intervals, or hesitancy terms instead of a single probability mass. Output is a graded status assessment carrying its own confidence.",
     "course": "Positioned against the course's probability axioms deliberately: where the course's frequentist machinery needs repeatable trials, project evidence is often one-shot and linguistic. These formalisms are the recognized extension for that regime (Zadeh, Shafer, Smarandache literatures).",
     "assumptions": "Membership functions / mass assignments are elicited design choices; the defense is comparative (do rankings remain stable across reasonable parameterizations \u2014 a sensitivity argument), not inferential.",
     "validation": "Each formalism is peer-reviewed decision-science literature with citable primary sources. Accreditation in PCEIF = published axioms + documented parameterization + sensitivity/stability checks, plus practitioner face-validation interviews.",
     "explainability": "Parameterization disclosure (membership functions / mass assignments with provenance) + stability table showing verdict invariance across parameter ranges.",
     "oversight": "Inform \u2014 comparative representations; production verdict comes from DST (7.1) within Cat 7.",
     "failureModes": "Arbitrary-seeming parameterization if provenance undocumented; formalism-shopping accusation (answered by the stability analysis); citation without computation (each must have a real compute path or be cut).",
     "detProb": "Deterministic: combination operators. Epistemic: membership/mass elicitation.",
     "applied": [
      {
       "name": "Reference Class Forecasting",
       "note": "Positions the project against an outside-view distribution of comparable projects (Flyvbjerg); output is a percentile placement.",
       "qa": [
        [
         "Where is your reference class data?",
         "Seeded from published overrun distributions for the sector; stated as an outside-view prior, exactly Kahneman/Flyvbjerg's accredited method for optimism-bias correction."
        ]
       ]
      },
      {
       "name": "Rough Sets",
       "note": "Lower/upper approximation of status classes given indiscernible evidence granules; boundary region = irreducible ambiguity.",
       "qa": []
      },
      {
       "name": "Neutrosophic Logic",
       "note": "Truth/indeterminacy/falsity triplet per status claim; indeterminacy made explicit rather than split between T/F.",
       "qa": []
      },
      {
       "name": "Interval Fuzzy Sets",
       "note": "Membership as an interval, encoding second-order uncertainty about the membership function itself.",
       "qa": []
      },
      {
       "name": "Z-numbers",
       "note": "Pairs (restriction, reliability): a status claim plus confidence in the source \u2014 the formal home of Cat 9 reliability weights.",
       "qa": []
      },
      {
       "name": "PLTS",
       "note": "Probabilistic linguistic term sets: distributions over linguistic labels (e.g., 60% 'stressed', 40% 'stable') from practitioner-style judgments.",
       "qa": []
      },
      {
       "name": "Plithogenic Sets",
       "note": "Multi-attribute membership with per-attribute contradiction degrees; suits multi-source project evidence.",
       "qa": []
      },
      {
       "name": "Belief Rule Base",
       "note": "IF-THEN rules with belief degrees; the auditable middle ground between expert rules and probabilistic inference.",
       "qa": []
      },
      {
       "name": "Quantum Probability",
       "note": "SOBER GROUNDING REQUIRED (open item): defensible only as non-commutative probability for order-effects in judgment (Busemeyer & Bruza literature) \u2014 NOT physics claims. If it cannot be grounded that way, cut it before the defense.",
       "qa": []
      },
      {
       "name": "Pythagorean Fuzzy Sets",
       "note": "Membership/non-membership with mu^2+nu^2<=1, a wider admissible region than intuitionistic sets.",
       "qa": []
      },
      {
       "name": "Picture Fuzzy Sets",
       "note": "Adds neutrality degree: yes/abstain/no/refusal \u2014 matching how practitioners actually vote on status.",
       "qa": []
      },
      {
       "name": "Hesitant Fuzzy Sets",
       "note": "Multiple candidate membership values when evaluators disagree; keeps the disagreement instead of averaging it away.",
       "qa": []
      },
      {
       "name": "Type-2 Fuzzy Sets",
       "note": "Fuzzy membership of membership: uncertainty about the band edges themselves \u2014 the formalism that owns the 'why 0.95?' question.",
       "qa": []
      },
      {
       "name": "Maximum Entropy",
       "note": "Least-committal distribution consistent with known constraints; the principled answer to missing information (and the anti-25/25/25/25 argument formalized).",
       "qa": []
      },
      {
       "name": "Possibility Theory",
       "note": "Possibility/necessity bounds; captures 'cannot be ruled out' vs 'must be' \u2014 natural for early-project sparse evidence.",
       "qa": []
      },
      {
       "name": "Spherical Fuzzy Sets",
       "note": "Membership/non-membership/hesitancy on the unit sphere; recent generalization with growing MCDM literature.",
       "qa": []
      },
      {
       "name": "Fermatean Fuzzy Sets",
       "note": "mu^3+nu^3<=1 admissible region; used where evaluations are strongly polarized.",
       "qa": []
      },
      {
       "name": "MARCOS Ranking",
       "note": "Compromise ranking against ideal/anti-ideal reference projects.",
       "qa": []
      },
      {
       "name": "CRITIC-TOPSIS",
       "note": "Objective criteria weighting (CRITIC: contrast + correlation) feeding TOPSIS distance-to-ideal ranking \u2014 the statistically grounded weighting in the MCDM pair.",
       "qa": []
      },
      {
       "name": "Hypersoft Sets",
       "note": "Parameter-family mappings for multi-attribute, multi-source evidence organization.",
       "qa": []
      }
     ]
    },
    {
     "key": "fusion",
     "label": "Evidence Fusion / Aggregation Rule",
     "uncertainty": "Combines per-module status votes into a category verdict. DST assigns basic probability masses to status hypotheses and combines them with Dempster's rule (Red weighted 1.5x); missing-input modules abstain (no mass) rather than injecting uniform 25/25/25/25 noise. Simpler rules (dominance, weighted voting, worst-N-of-M) are transparent aggregation baselines.",
     "course": "Connects to the course's law of total probability and to combining independent evidence; DST generalizes Bayes by allowing mass on sets of hypotheses (ignorance) \u2014 the formal answer to 'what if a module has no data?'",
     "assumptions": "Dempster's rule assumes evidential independence between modules; correlated modules (several EVM ratios share EV/AC) can double-count \u2014 mitigated by the 1.5x Red weighting design and conservative dominance at project level.",
     "validation": "Shafer (1976) primary source. Validated by the fusion-table unit tests and by the calibration probe protocol (known-band document sets must reproduce target category status).",
     "explainability": "Evidence chain: per-module votes, masses, abstentions, combined masses, and final verdict \u2014 a complete audit trail per category per period.",
     "oversight": "Recommend \u2014 fused status is the platform's principal recommendation; human governance layer (Judgment Record 4.21) records concur/override.",
     "failureModes": "Zadeh conflict pathology; correlated-evidence double counting; source-table gaps (the live evmMin 0.90\u20130.95 Yellow-mass defect); mass-normalization bugs.",
     "detProb": "Deterministic: combination rule. Epistemic: mass assignments per status hypothesis.",
     "applied": [
      {
       "name": "Conservative Dominance",
       "note": "Project status = worst category. A max-type aggregation guaranteeing no masking.",
       "qa": [
        [
         "Too conservative?",
         "Chosen policy for a governance instrument: the cost asymmetry between missed Red and false Amber justifies a minimax posture \u2014 a decision-theoretic, not statistical, argument, stated as such."
        ]
       ]
      },
      {
       "name": "Weighted Voting",
       "note": "Mass-weighted category vote; Red 1.5x.",
       "qa": [
        [
         "Why 1.5?",
         "Sensitivity-tested: rankings stable for weights 1.3-1.8; 1.5 sits mid-plateau. The stability analysis is the defense, not the number."
        ]
       ]
      },
      {
       "name": "Majority Rules",
       "note": "Simple-majority baseline aggregator.",
       "qa": [
        [
         "Purpose?",
         "A transparency baseline \u2014 showing fused verdicts against the naive rule quantifies what the sophisticated fusion adds."
        ]
       ]
      },
      {
       "name": "Worst-N-of-M",
       "note": "Escalate if >=N modules of M are at/below a status.",
       "qa": [
        [
         "Relation to order statistics?",
         "It is a threshold on an order statistic of module votes \u2014 directly analyzable for false-alarm behavior under independence assumptions."
        ]
       ]
      },
      {
       "name": "Dempster-Shafer",
       "note": "The production fusion engine: masses per status, Dempster combination, abstention for missing inputs, Red 1.5x. The known open issue: fusion source table has no Yellow mass for evmMin 0.90-0.95 (probe protocol decides docs-vs-table fix).",
       "qa": [
        [
         "Dempster's rule with conflicting evidence?",
         "Known Zadeh critique: high conflict can yield counterintuitive combinations. Mitigations: abstention removes vacuous mass, Red-weighting biases conservative, and conservative dominance caps the damage at project level. Critique and mitigations both documented."
        ],
        [
         "Why no Yellow mass at evmMin 0.90-0.95?",
         "Open defect under probe: if the PRJ-21476 Yellow set fuses to Amber, the fix is one line in the fusion source table \u2014 evidence the calibration protocol works as designed."
        ]
       ]
      }
     ]
    }
   ]
  }
 ],
 "praxisOutline": {
  "heading": "The Praxis Behind the Platform",
  "lead": "Lin Opus Gubernatio is the proof-of-concept instrument for a Doctor of Engineering praxis on AI-driven probabilistic governance for public capital project controls. The research problem is the signal-to-action gap: modern platforms generate predictive signals faster than public-sector governance can responsibly act on them. PCEIF closes that gap by pairing every analytical signal with governed human judgment.",
  "chapters": [
   [
    "Introduction",
    "Frames public AEC capital programs as decision systems and defines the signal-to-action gap: why signal generation alone is not governance, and why public-sector constraints of accountability, auditability, fairness, and procurement shape the design."
   ],
   [
    "Literature, Theory, Standards, and Technology",
    "Grounds the framework in earned value management and its limits, predictive project controls, public-sector AI governance, and theoretical lenses including bounded rationality, sociotechnical systems, procedural justice, and human judgment under multi-signal uncertainty: automation bias, algorithm aversion, anchoring, alert fatigue, and trust calibration."
   ],
   [
    "Research Methodology",
    "Design Science Research: the framework and instrument are built as artifacts and evaluated through structured practitioner validation rather than statistical hypothesis testing on outcomes."
   ],
   [
    "The PCEIF Governance Framework",
    "The governance architecture itself: signal packages routed to human review, conflict kept visible, and the Human Judgment Record with mandatory rationale capture, no silent overrides, an override taxonomy, and a judgment ledger whose patterns become learning inputs."
   ],
   [
    "Analytical Module Taxonomy",
    "The full capability taxonomy behind this handbook: ten project categories plus the Portfolio Health suite, each documented with its governance role, its human judgment risks, its module register, and validation questions."
   ],
   [
    "The Proof-of-Concept Instrument",
    "Lin Opus Gubernatio as built: document ingestion, signal extraction, probabilistic computation, evidence fusion, and the executive interfaces that surface every red signal regardless of overall status."
   ],
   [
    "Practitioner Validation and Refinement",
    "Twelve or more professionals across owner, contractor, and consultancy roles evaluate the framework qualitatively; their feedback drives framework refinement and defines the boundary of claims."
   ]
  ],
  "judgmentLayer": "Every capability in this handbook outputs evidence, not instructions. A module must expose its source, abstain when required inputs are absent, and enter a signal package that a project manager may accept, override, defer, or escalate. The judgment and its rationale become part of the audit record. Analytical transparency plus governed professional discretion is the design thesis of the entire praxis."
 }
};
